"""
Shared agent state definition for the Job Hunting Agent.

This module defines the TypedDict that flows through every node
in the LangGraph workflow. It is kept in its own file to avoid
circular imports between node modules.
"""

from typing import List, Dict, Any
from pydantic import BaseModel, Field


class AgentState(BaseModel):
    """State that flows through the LangGraph workflow.

    Attributes:
        resume_path: Filesystem path to the uploaded resume file.
        resume_text: Extracted plain-text content of the resume.
        search_queries: Job search queries generated by the LLM.
        job_listings: Raw job listings returned by the search step.
        ranked_jobs: Final ranked output produced by the ranking step.
    """
    resume_path: str = Field(default="")
    resume_text: str = Field(default="")
    search_queries: List[str] = Field(default_factory=list)
    job_listings: List[Dict[str, Any]] = Field(default_factory=list)
    ranked_jobs: str = Field(default="")
